version: '2'
services:
  api:
    image: htm-api
    container_name: "htm-api"
    command: npm run start
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
      - "8080:3000"
    links:
      - redis
      - mongo
  redis:
    image: redis
    container_name: "htm-redis"
    volumes:
      - ./cache/redis:/data
    ports:
      - "6379:6379"
    command: [
      "bash", "-c",
      '
        docker-entrypoint.sh
        --appendonly yes
        --requirepass ${REDIS_PASSWORD}
      '
    ]
  mongo:
    image: mongo:3.0-wheezy
    container_name: "htm-db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
